### ISSUE TITLE
agwscapi.exe crashing repeatedly

### ISSUE THREAD

**Issue by halkon** [appgate/sdp-wscapi#1]
Found some logs when using SDP that point to this error message:

```
application/log.log:[2020-10-26T15:40:39.423Z] Info : Authentication succeeded. Claims Token: [TokenId: ..., DistinguishedName: CN=...,CN=...,OU=ADFS, ExpirationTime: 10/27/2020 3:40:39 AM], On-demand Claims: [[Command: runScript, ClaimName: avcheck, Parameters: [[args, -av], [name, win_sec_center_query]], Command: fileExists, ClaimName: SCCMClientInstalled, Parameters: [[path, C:\Windows\CCM\CcmExec.exe]], Command: runScript, ClaimName: CrowdStrikeWin, Parameters: [[args, ], [name, win croudstrike check]]]], Device Scripts: [[Name: win_sec_center_query, Filename: agwscapi.exe, Checksum: ..., ChecksumSha256: ..., Name: win croudstrike check, Filename: wincs-check.ps1, Checksum: ..., ChecksumSha256: ...]]
application/log.log:[2020-10-26T15:40:40.096Z] Info : Saving device script to 'C:\ProgramData\AppGate\Scripts\agwscapi.exe'.
application/log.log:[2020-10-26T15:40:45.238Z] Warn : Process 'C:\ProgramData\AppGate\Scripts\agwscapi.exe -av' took longer than the timeout of 5000 milliseconds. Killing it.
```

is there any indication to what we can further do to help it not timeout or crash and pop up an error message?

**Comment by halkon** [comment]
@Mar8x seems you're doing some committing here, any kind of pointers, even a "no idea, good luck" would be helpful. 

Thanks

**Comment by Mar8x** [comment]
Hi @halkon and sorry for the delay, this was not on purpose to keep you waiting.

` took longer than the timeout of 5000 milliseconds` indicating the agwscapi.exe took longer to complete than 5sec (so appgate client killed it). Can you run it on that machine manually and see if it eventually succeeds?

**Comment by halkon** [comment]
@Mar8x if I run:

```powershell
C:\ProgramData\AppGate\Scripts\agwscapi.exe -av
``` 
directly in an administrator powershell, it immediately gives me the windows prompt that it stopped responding, as soon as I hit enter.

**Comment by halkon** [comment]
![image](https://user-images.githubusercontent.com/1437154/98567553-b057e380-2275-11eb-831c-932a0ecbbe17.png)

**Comment by Mar8x** [comment]
@halkon two things:
(1) it terminates without any output, is that expected; (what OS version? What does `-fw` shows?)
(2) it might be a privilege issue when the client runs the exe. Are you using the latest client?

**Comment by halkon** [comment]
Let me answer all the questions at once with a screenshot:

![image](https://user-images.githubusercontent.com/1437154/98598345-f5910b00-229f-11eb-996e-8c53ff6b6072.png)


This is a fresh install of the client, that error message after the second `-fw` call I am unable to reproduce, any of the calls always crash `agwscapi`.

As far as OS:

```OS Name	Microsoft Windows Server 2016 Datacenter
Version	10.0.14393 Build 14393
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
```

The image is an AWS EC2 base image

**Comment by Mar8x** [comment]
It seems it does not like that os; well, it seems there is no Windows Security Center, isn't it?
How does https://github.com/appgate/sdp-windows-check
`devicecheck.exe -isavok` behave? It might not run because of missing DLL/COM.

 At least the program should not crash, but notify. I will have a look, but cannot commit to a time.

**Comment by Mar8x** [comment]
@halkon There is a new version of the exe, it should not crash anymore but will for sure not be useful since there is not WSC.

BTW I verified on `  AWS, OS 10.0.14393.3986` (Server 2016)

**Comment by halkon** [comment]
Thank you so much @Mar8x sorry about my lack of response.  You are correct, no Windows Security Center. 

```powershell
PS C:\Users\Administrator.RS1\Downloads> ./devicecheck.exe -isavok
no
```

I'll try the new release and see how well it works.  

Thanks

**Comment by halkon** [comment]
So far, no annoying crashing pop ups 👍 thank you for the update!

**Comment by Mar8x** [comment]
Great and thank you for reporting the issue.
